### ISSUE TITLE
recognized_object_array not published

### ISSUE THREAD

**Issue by siamak-p** [wg-perception/ork_tutorials#13]
hello guys
I'm new in ros and ork
I installed ubuntu 14.0.4 and ros indigo and ORK successfully.
when i run following code, recognized_object_array not published.

CODE:
rosrun object_recognition_core detection -c `rospack find object_recognition_tabletop`/conf/detection.table.ros.ork

RESULT:
[ INFO] [1473240713.048836820]: Initialized ROS. node_name: /object_recognition_server
[ INFO] [1473240713.410736958]: System already initialized. node_name: /object_recognition_server
[ INFO] [1473240713.421767359]: Subscribed to topic:/camera/depth_registered/camera_info [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1473240713.425730339]: Subscribed to topic:/camera/rgb/image_color [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1473240713.430732342]: Subscribed to topic:/camera/rgb/camera_info [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1473240713.435740943]: Subscribed to topic:/camera/depth_registered/image_raw [queue_size: 1][tcp_nodelay: 0]
126 :: 0.5 , 1 , 0.995004 , /base_link , /head_mount_kinect_rgb_optical_frame
[ INFO] [1473240713.856739924]: publishing to topic:/tabletop/clusters
[ INFO] [1473240713.857888589]: publishing to topic:/table_array

How can i fix it?
Any help you could give would be greatly appreciated.
Very Respectfully,
Siamak

**Comment by hris2003** [comment]
Please consult the [tutorial about tabletop](https://wg-perception.github.io/ork_tutorials/tutorial02/tutorial.html#finding-objects) for a correct use.

**Comment by siamak-p** [comment]
thank you. I changed my some packages and that's gonna OK.
