### ISSUE TITLE
Failed to detect object when adding another .stl file to couchDB

### ISSUE THREAD

**Issue by HaoLi-China** [wg-perception/ork_tutorials#2]
My OS is ubuntu12.04 64 bits. And my ros is hydro. I haved added coke.stl which is downloaded from "https://github.com/wg-perception/ork_tutorials/tree/master/data" to couchDB.It is ok when I excuted command following:
$:rosrun object_recognition_core detection -c `rospack find object_recognition_tabletop`/conf/detection.object.ros.ork --visualize
It showed these info:

[ INFO] [1398159793.144601128]: Initialized ROS. node_name: /object_recognition_server
[ INFO] [1398159793.414516596]: System already initialized. node_name: /object_recognition_server
[ INFO] [1398159793.679336505]: System already initialized. node_name: /object_recognition_server
[ INFO] [1398159793.685019973]: Subscribed to topic:/camera/rgb/camera_info with queue size of 1
[ INFO] [1398159793.686344064]: Subscribed to topic:/camera/depth_registered/camera_info with queue size of 1
[ INFO] [1398159793.687766839]: Subscribed to topic:/camera/depth_registered/image_raw with queue size of 1
[ INFO] [1398159793.689116115]: Subscribed to topic:/camera/rgb/image_color with queue size of 1
126 :: 0.5 , 1 , 0.995004 , /base_link , /head_mount_kinect_rgb_optical_frame
Loading model: ce9e0cc66e1bc8b48e6153c3210190ec for object id: ce9e0cc66e1bc8b48e6153c321018bb4Info,  T0: Load /tmp/fileIVFPGX.stl
Info,  T0: Found a matching importer for this file format
Info,  T0: Import root directory is '/tmp/'
Info,  T0: Entering post processing pipeline
Warn,  T0: RemoveVCProcess: AI_CONFIG_PP_RVC_FLAGS is zero.
Info,  T0: Points: 0, Lines: 0, Triangles: 1, Polygons: 0 (Meshes, X = removed)
Info,  T0: JoinVerticesProcess finished | Verts in: 1536 out: 1192 | ~22.4%
Info,  T0: Cache relevant are 1 meshes (512 faces). Average output ACMR is 2.332031
Info,  T0: Leaving post processing pipeline

[ INFO] [1398159797.394224297]: publishing to topic:/tabletop/clusters
[ INFO] [1398159797.395410642]: publishing to topic:/table_array
[ INFO] [1398159797.402247634]: publishing to topic:/recognized_object_array

And it can really detect the coke when I runned my rviz.

Howerver,it failed when I added coffecup.stl which is downloaded from "http://www.thingiverse.com/thing:32305" to couchDB. It only showed these info and stopped without showing info about "publishing to topic:***":

[ INFO] [1398168723.528327357]: Initialized ROS. node_name: /object_recognition_server
[ INFO] [1398168723.794185754]: System already initialized. node_name: /object_recognition_server
[ INFO] [1398168724.053566849]: System already initialized. node_name: /object_recognition_server
[ INFO] [1398168724.059169147]: Subscribed to topic:/camera/depth_registered/camera_info with queue size of 1
[ INFO] [1398168724.060668587]: Subscribed to topic:/camera/rgb/camera_info with queue size of 1
[ INFO] [1398168724.062016139]: Subscribed to topic:/camera/rgb/image_color with queue size of 1
[ INFO] [1398168724.063365166]: Subscribed to topic:/camera/depth_registered/image_raw with queue size of 1
126 :: 0.5 , 1 , 0.995004 , /base_link , /head_mount_kinect_rgb_optical_frame
Loading model: ce9e0cc66e1bc8b48e6153c32101abd7 for object id: ce9e0cc66e1bc8b48e6153c321019e9eInfo,  T0: Load /tmp/fileZNgaFd.stl
Info,  T0: Found a matching importer for this file format
Info,  T0: Import root directory is '/tmp/'
Info,  T0: Entering post processing pipeline
Warn,  T0: RemoveVCProcess: AI_CONFIG_PP_RVC_FLAGS is zero.
Info,  T0: Points: 0, Lines: 0, Triangles: 1, Polygons: 0 (Meshes, X = removed)
Info,  T0: JoinVerticesProcess finished | Verts in: 5262 out: 4238 | ~19.5%
Info,  T0: Cache relevant are 1 meshes (1754 faces). Average output ACMR is 2.425313
Info,  T0: Leaving post processing pipeline

And topics,such as"/tabletop/clusters","/table_array" and "/recognized_object_array", do not exist.

**Comment by mashevictor** [comment]
maybe because the file you downloaded is too big.

**Comment by mashevictor** [comment]
https://drive.google.com/drive/folders/18GXWu_mJ2SnKy8aKAfdbRlv7WuMw9cjT

you can download this file...
The program can train and detect this small stl...remember ,small.
